version: '3.8'

services:
  # ──────────────────────────────────────────────────
  # 1) Laravel app (sales)
  # ──────────────────────────────────────────────────
  sales-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sales_app
    restart: on-failure
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - sales_network
      - shared_services_network
    depends_on:
      - sales-db
    env_file:
      - .env
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CONNECTION=database
    extra_hosts:
      - "myinvoice.local:172.18.0.2"
    healthcheck:
      test: ["CMD", "php", "-r", "echo @fsockopen('localhost', 9000) ? 'Healthy' : 'Unhealthy';"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  # ──────────────────────────────────────────────────
  # 2) Nginx (web server)
  # ──────────────────────────────────────────────────
  sales-webserver:
    image: nginx:latest
    container_name: sales_webserver
    restart: on-failure
    ports:
      - "8001:80"
      - "8444:443"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs 
    networks:
      - sales_network
      - shared_services_network
    depends_on:
      - sales-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # ──────────────────────────────────────────────────
  # 3) Mysql (database server)
  # ──────────────────────────────────────────────────
  sales-db:
    image: mysql:8.0
    container_name: sales_db
    restart: on-failure
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sales_network
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  # ─────────────────────────────────────────────────────────────────
  # 4) Queue‐worker
  # ─────────────────────────────────────────────────────────────────app:
  sales-queue_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sales_queue_worker
    working_dir: /var/www/html
    restart: unless-stopped
    command: php artisan queue:work --queue=default --tries=3 --timeout=60
    volumes:
      - .:/var/www/html
    networks:
      - sales_network
    depends_on:
      sales-app: # Worker needs the app code
        condition: service_started
      sales-db:  # Worker connects to the database for jobs
        condition: service_healthy
    env_file:
      - .env
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CONNECTION=database
    extra_hosts:
      - "myinvoice.local:172.18.0.2"
    healthcheck:
      test: ["CMD", "php", "-r", "echo @fsockopen('localhost', 9000) ? 'Healthy' : 'Unhealthy';"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  laravel_app:
  mysql_data:

networks:
  sales_network:
    driver: bridge
  shared_services_network:
    name: shared-services-network
    external: true
