name: Restrict PRs into main (only from develop or hotfix/*)

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          echo "Source branch: ${{ github.head_ref }}"

          if [[ "${{ github.head_ref }}" == "develop" ]]; then
            echo "✅ Allowed: PR from develop"
            exit 0
          fi

          if [[ "${{ github.head_ref }}" == hotfix/* ]]; then
            echo "✅ Allowed: PR from hotfix"
            exit 0
          fi

          echo "❌ Blocked: Only 'develop' or 'hotfix/*' branches may merge into 'main'."
          exit 1
