name: Deploy Laravel Invoice App on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy to Droplet
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: checkout
        uses: actions/checkout@v4

      # 2. Start an SSH agent and add the private key
      - name: setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Optionally add your host to known_hosts to avoid strict-check failures
      - name: add droplet to known_hosts
        run: |
          ssh-keyscan -p ${SSH_PORT:-22} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # 4. SSH in and pull & build
      - name: deploy via SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          ssh -o StrictHostKeyChecking=yes \
              -p ${SSH_PORT:-22} \
              $SSH_USER@$SSH_HOST << 'EOF'
            
            set -e

            # go to your Laravel public folder
            cd /var/www/nur-ddd-sales-app

            # pull the latest
            git fetch --all
            git reset --hard origin/main

            # install & optimize
            composer install --no-dev --optimize-autoloader

            # run migrations
            php artisan migrate

            # cache config/routes/views
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "✔ Deployment successful!"
            EOF
