name: Validate PR into main (only allow from develop or hotfix/*)

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.branch-check.outputs.valid }}

    steps:
      - id: branch-check
        run: |
          if [[ "${{ github.head_ref }}" == "develop" ]] || [[ "${{ github.head_ref }}" == hotfix/* ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
            exit 1
          fi
