name: Verify main branch PR ( develop or hotfix/*)

on:
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.branch-check.outputs.valid }}

    steps:
      - id: branch-check
        run: |
          if [[ "${{ github.head_ref }}" == "develop" ]] || [[ "${{ github.head_ref }}" == hotfix/* ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "valid=false" >> $GITHUB_OUTPUT
            exit 1
          fi
