name: Validate PR Source to Main

on:
  pull_request:
    branches:
      - main  # ✅ Only trigger for PRs targeting main

jobs:
  validate-pr-source:
    name: Validate Source Branch  # ✅ This name will appear in "Required status checks"
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR source is develop or hotfix/*
        run: |
          BRANCH="${{ github.head_ref }}"

          if [[ "$BRANCH" == "develop" || "$BRANCH" == hotfix/* ]]; then
            echo "✅ Valid source branch: $BRANCH"
            exit 0
          fi

          echo "❌ Invalid source branch: $BRANCH"
          echo "Only 'develop' or 'hotfix/*' branches may target 'main'"
          exit 1
